# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('horario_idsala', models.IntegerField()),
                ('horario_date', models.DateField()),
                ('horario_time', models.TimeField()),
                ('horario_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('insumo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('insumo_idsala', models.IntegerField()),
                ('insumos_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reserva_date', models.DateField()),
                ('reserva_starttime', models.TimeField()),
                ('reserva_endtime', models.TimeField()),
                ('reserva_capacity', models.IntegerField()),
                ('reserva_idinsumo', models.IntegerField()),
                ('reserva_idsala', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sala_name', models.CharField(max_length=50)),
                ('sala_location', models.CharField(max_length=50)),
                ('sala_status', models.IntegerField()),
                ('sala_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario_name', models.CharField(max_length=75)),
                ('usuario_pass', models.CharField(max_length=12)),
                ('usuario_role', models.IntegerField()),
                ('usuario_mail', models.CharField(max_length=200)),
            ],
        ),
    ]
